-- Sample generated artifact: the backward-compatible shim Pathfinder drafts for
-- the `orders.customer_id` -> `cust_id` rename. Keeping the old name as an alias
-- lets the downstream consumers keep resolving while their owners migrate.
--
-- Generated by: pathfinder run --before ... --after ... --dataset orders

-- Pathfinder shim for `orders`: keep `customer_id` available while consumers
-- migrate to `cust_id`. Remove after all downstream owners have moved.
select
    *,
    cust_id as customer_id  -- deprecated alias
from {{ ref('orders') }}
